@baseUrl = http://localhost:3000

###
POST {{baseUrl}}/user/login
Host: www.anu.local
Content-Type: application/json

{
  "email": "markmagdy148@gmail.com",
  "password": "aaAA11!!"
}


### Create Staff Account (with file upload)
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJtYXJrbWFnZHkxNDhAZ21haWwuY29tIiwidGVuYW50X25hbWUiOiJhbGV4YW5kcmlhIG5hdGlvbmFsIHVuaXZlcnNpdHkiLCJyb2xlcyI6WyJSb290Il0sInBlcm1pc3Npb25zIjpbInJvbGUuY3JlYXRlIiwicm9sZS5yZWFkIiwicm9sZS51cGRhdGUiLCJyb2xlLmRlbGV0ZSIsImFjY291bnQuY3JlYXRlIiwiYWNjb3VudC5yZWFkIiwiYWNjb3VudC51cGRhdGUiLCJhY2NvdW50LmRlbGV0ZSIsImFjY291bnQuYXNzaWduX3JvbGUiXSwiaWF0IjoxNzcxMTY3OTkyLCJleHAiOjE3NzEyNTQzOTJ9.ZlfUzkRXO8fbFPSTQuTiB3cZXth7Fpy1IdGhWj3OpEo

POST {{baseUrl}}/api/user/account/staff
Content-Type: application/json
Authorization: Bearer {{token}}
X-Tenant-Id: Alexandria National University

{
  "username": "ahmed_salem",
  "first_name": "Ahmed",
  "last_name": "Salem",
  "email": "ahmed.salem@example.com",
  "password": "aaAA11!!",
  "phone": "+201112223344",
  "date_of_birth": "1995-11-20",
  "address": "45 El Nasr Road",
  "city": "Alexandria",
  "country": "Egypt",
  "national_id": "29511204567891",
  "position": "HR Specialist",
  "hireDate": "2024-09-15",
  "salary": "9200.00"
}



