import { Prisma, PrismaClient, Program, ProgramLevel } from "@prisma/client";
import { CreateProgramRequestDto } from "../Interfaces/Program/Create/CreateProgramSchema";
import { UpdateProgramRequestDto } from "../Interfaces/Program/Update/UpdateProgramSchema";

type DbClient = PrismaClient | Prisma.TransactionClient;

export class ProgramRepository {

  // To make controllers/services get a consistent program shape.
  // flow updated to relies on programLevels to clean dependent rows before rebuild.
  // private static readonly programDetailsInclude = {
  //   faculty: true,
  //   head: { include: { user: true } },
  //   programLevels: { include: { fees: {} } },
  //   programTranscriptDefs: true,
  //   // academicLoadSemesters: { include: { semester: true, programLevel: true } },
  //   academicLoadGPAs: true,
  //   programCourses: { include: { course: true } },
  // } as const;

  static async CreateProgram(input: CreateProgramRequestDto, prisma: PrismaClient) {

    return await prisma.$transaction(async (tx) => {
      // 1. Create the Program and its Levels first
      // We do this to get the Level IDs generated by the DB
      const program = await tx.program.create({
        data: {
          name: input.name,
          description: input.description,
          facultyId: input.facultyId,
          headId: input.headId,
          phone: input.phone,
          universityCreditHours: input.universityCreditHours,
          facultyCreditHours: input.facultyCreditHours,
          programCreditHours: input.programCreditHours,
          programType: input.programType,
          resultDisplay: input.resultDisplay,

          // Nested creation for things that 
          programTranscriptDefs: {
            createMany: {
              data: input.transcriptDefinition.map(td => ({
                gradeLetter: td.gradeLetter,
                minScore: td.minScore,
                maxScore: td.maxScore,
                minGpa: td.minGPA,
                maxGpa: td.maxGPA,
                equivalentEstimate: td.equivalentEstimate,
              }))
            }
          },
          academicLoadGPAs: {
            createMany: {
              data: input.academicLoadGPA.map(gpa => ({
                minGpa: gpa.minGPA,
                maxGpa: gpa.maxGPA,
                minCredits: gpa.minCredits,
                maxCredits: gpa.maxCredits,
              }))
            }
          },
          programLevels: {
            create: input.levels.map(level => ({
              level: level.level,
              minCredits: level.minCredits,
              maxCredits: level.maxCredits,
            }))
          }
        },
        include: {
          programLevels: true, // We need these IDs for the next step
          faculty: { select: { name: true } },
          head: { select: { user: { select: { firstName: true, lastName: true } } } }
        }
      });

      // 2. Map the generated Level IDs to their Level Numbers
      const levelIdMap = new Map(program.programLevels.map(l => [l.level, l.id]));

      // 3. Prepare Bulk Inserts for Fees and Semester Loads
      const feeData: Prisma.FeeCreateManyInput[] = [];
      const semesterLoadData: Prisma.AcademicLoadSemesterCreateManyInput[] = [];

      for (const levelInput of input.levels) {
        const levelId = levelIdMap.get(levelInput.level)!;

        // Flatten Fees
        feeData.push(
          ...levelInput.semesterFees.semester1.map(f => ({ ...f, semesterNumber: 1, programLevelId: levelId })),
          ...levelInput.semesterFees.semester2.map(f => ({ ...f, semesterNumber: 2, programLevelId: levelId })),
          ...levelInput.summerFees.map(f => ({ ...f, semesterNumber: 3, programLevelId: levelId }))
        );

        // Filter and map Semester Loads for this specific level
        const relevantLoads = input.academicLoadSemester
          .filter(s => s.level === levelInput.level)
          .map(s => ({
            programId: program.id,
            programLevelId: levelId,
            semesterNumber: s.semester,
            minCredits: s.minCredits,
            maxCredits: s.maxCredits,
          }));

        semesterLoadData.push(...relevantLoads);
      }

      // 4. Final Batch Inserts
      await Promise.all([
        tx.fee.createMany({ data: feeData }),
        tx.academicLoadSemester.createMany({ data: semesterLoadData })
      ]);

      return program;
    });
  }

  static async GetAllPrograms(prisma: DbClient) {
    return prisma.program.findMany({
      select: {
        id: true, name: true, facultyId: true, headId: true,
        programType: true, programCreditHours: true, universityCreditHours: true, facultyCreditHours: true,
        phone: true, description: true,
        programLevels: {
          select: {
            id: true,
            level: true, fees: {
              omit: { updatedAt: true, createdAt: true, programLevelId: true }
            }
          }
        }, programTranscriptDefs: true,
      },
      orderBy: [{ name: "asc" }],
    });
  }

  static async GetProgramById(id: number, prisma: DbClient) {
    return prisma.program.findUnique({
      where: { id },
      select: {
        id: true,
        name: true,
        facultyId: true,
        phone: true,
        programType: true,
        description: true,
        programLevels: {
          select: {
            id: true,
            level: true,
            minCredits: true,
            maxCredits: true,
            fees: {
              omit: { updatedAt: true, createdAt: true, programLevelId: true },
            },
          },
          orderBy: { level: "asc" },
        },
      }
    });
  }

  /**
   * Updates a program and all its nested relations using a non-destructive
   * sync pattern for structural data and a destructive pattern for configuration data.
   */
  static async UpdateProgram(programId: number, data: UpdateProgramRequestDto, prisma: DbClient) {
    return await prisma.$transaction(async (tx: any) => {

      // 1. Update Core Program Scalars
      await tx.program.update({
        where: { id: programId },
        data: {
          name: data.name,
          description: data.description,
          phone: data.phone,
          universityCreditHours: data.universityCreditHours,
          facultyCreditHours: data.facultyCreditHours,
          programCreditHours: data.programCreditHours,
          programType: data.programType,
          resultDisplay: data.resultDisplay,
          durationYears: data.levelsNumber, // Corrected from levelsNumber
          faculty: data.facultyId ? { connect: { id: data.facultyId } } : undefined,
          head: data.headId ? { connect: { userId: data.headId } } : { disconnect: true },
        },
      });

      // 2. Sync Program Levels (Keep track of IDs for Step 3)
      const levelIdMap = new Map<number, number>(); // levelNumber -> databaseId

      if (data.levels) {
        // Explicitly type 'l' to avoid the 'any' error
        const incomingLevelIds = data.levels
          .map((l: any) => l.id)
          .filter((id): id is number => !!id);

        await tx.programLevel.deleteMany({
          where: { programId, id: { notIn: incomingLevelIds } },
        });

        for (const level of data.levels) {
          // Flatten fees logic...
          const rawFees = [
            ...(level.fees || []).map(f => ({ ...f, semesterNumber: 0 })),
            ...(level.semesterFees?.semester1 || []).map(f => ({ ...f, semesterNumber: 1 })),
            ...(level.semesterFees?.semester2 || []).map(f => ({ ...f, semesterNumber: 2 })),
            ...(level.summerFees || []).map(f => ({ ...f, semesterNumber: 3 })),
          ];

          const uniqueFeesMap = new Map();
          for (const f of rawFees) {
            uniqueFeesMap.set(`${f.semesterNumber}-${f.feeType}`, {
              feeType: f.feeType,
              amount: f.amount,
              semesterNumber: f.semesterNumber,
              description: f.description || null,
            });
          }

          // --- TYPING FIX START ---
          let levelDbId: number;

          if (level.id) {
            // Logic for existing levels
            await tx.programLevel.update({
              where: { id: level.id },
              data: {
                level: level.level,
                minCredits: level.minCredits ?? 0,
                maxCredits: level.maxCredits ?? 0
              },
            });

            await tx.fee.deleteMany({ where: { programLevelId: level.id } });

            if (uniqueFeesMap.size > 0) {
              await tx.fee.createMany({
                data: Array.from(uniqueFeesMap.values()).map(f => ({
                  ...f,
                  programLevelId: level.id as number // Type cast to confirm it's not undefined
                })),
              });
            }
            levelDbId = level.id; // We know it's a number because we're in the 'if(level.id)' block
          } else {
            // Logic for new levels
            const newLevel = await tx.programLevel.create({
              data: {
                level: level.level,
                minCredits: level.minCredits ?? 0,
                maxCredits: level.maxCredits ?? 0,
                program: { connect: { id: programId } },
                fees: { create: Array.from(uniqueFeesMap.values()) },
              },
            });
            levelDbId = newLevel.id;
          }

          // Now TypeScript is happy because levelDbId is guaranteed to be a number
          levelIdMap.set(level.level, levelDbId);
          // --- TYPING FIX END ---
        }
      } else {
        // If levels weren't sent, fetch existing ones and type the parameter 'l'
        const existingLevels = await tx.programLevel.findMany({ where: { programId } });
        existingLevels.forEach((l: { level: number; id: number }) => {
          levelIdMap.set(l.level, l.id);
        });
      }

      // 3. Sync Academic Load Semesters (The "No-Fail" Approach)
      if (data.academicLoadSemester) {
        // A. Deduplicate the incoming array right now
        // This prevents crashes if the frontend accidentally sends Level 1, Sem 1 twice.
        const uniqueLoadsMap = new Map<string, any>();

        for (const load of data.academicLoadSemester) {
          const key = `${load.level}-${load.semester}`;
          uniqueLoadsMap.set(key, load);
        }

        // B. Wipe the slate clean for this program
        await tx.academicLoadSemester.deleteMany({
          where: { programId },
        });

        // C. Insert the unique items
        for (const load of uniqueLoadsMap.values()) {
          const levelDbId = levelIdMap.get(load.level);

          // Skip if we can't find the level in our levelIdMap
          if (!levelDbId) {
            console.warn(`Skipping load: Level ${load.level} not found in levelIdMap`);
            continue;
          }

          await tx.academicLoadSemester.create({
            data: {
              semesterNumber: load.semester,
              minCredits: load.minCredits,
              maxCredits: load.maxCredits,
              program: { connect: { id: programId } },
              programLevel: { connect: { id: levelDbId } }
            },
          });
        }
      }

      // 4. Sync Academic Load GPA (Clean Wipe Approach)
      if (data.academicLoadGPA) {
        // Wipe existing GPA rules
        await tx.academicLoadGPA.deleteMany({
          where: { programId },
        });

        // Create new ones
        for (const gpaLoad of data.academicLoadGPA) {
          await tx.academicLoadGPA.create({
            data: {
              minGpa: gpaLoad.minGPA,
              maxGpa: gpaLoad.maxGPA,
              minCredits: gpaLoad.minCredits,
              maxCredits: gpaLoad.maxCredits,
              program: { connect: { id: programId } }
            },
          });
        }
      }

      // 5. Sync Transcript Definitions
      if (data.transcriptDefinition) {
        await tx.programTranscriptDefinition.deleteMany({ where: { programId } });
        await tx.programTranscriptDefinition.createMany({
          data: data.transcriptDefinition.map((td) => ({
            minScore: td.minScore,
            maxScore: td.maxScore,
            minGpa: td.minGPA,
            maxGpa: td.maxGPA,
            gradeLetter: td.gradeLetter,
            equivalentEstimate: td.equivalentEstimate,
            programId, // createMany usually allows raw programId
          })),
        });
      }

      return await tx.program.findUnique({
        where: { id: programId },
        include: {
          programLevels: { include: { fees: true } },
          academicLoadSemesters: true,
          academicLoadGPAs: true,
          programTranscriptDefs: true,
        },
      });
    },{
      timeout: 20000 
    });
    
  }


  static async DeleteProgramById(id: number, prisma: DbClient) {
    await prisma.program.delete({ where: { id } });
  }

  public static async ProgramExists(
    programId: number,
    prisma: PrismaClient | Prisma.TransactionClient
  ): Promise<boolean> {
    const program = await prisma.program.findUnique({
      where: { id: programId },
      select: { id: true }
    });
    return program !== null;
  }

  public static async GetProgramLevelById(
    programLevelId: number,
    prisma: PrismaClient | Prisma.TransactionClient,
    selectColumns?: Array<keyof Prisma.ProgramLevelSelect>
  ): Promise<Partial<ProgramLevel> | null> {
    const select: Prisma.ProgramLevelSelect = {};

    if (selectColumns && selectColumns.length > 0) {
      selectColumns.forEach((col) => {
        select[col] = true;
      });
    } else {
      select.id = true;
      select.programId = true;
    }
    return prisma.programLevel.findUnique({
      where: { id: programLevelId },
      select,
    });
  }

  public static async IsProgramLevelBelongsToProgram(
    programLevelId: number,
    programId: number,
    prisma: PrismaClient
  ): Promise<boolean> {
    const programLevel = await prisma.programLevel.findUnique({
      where: {
        id_programId: {
          id: programLevelId,
          programId: programId,
        },
      },
      select: { id: true },
    });

    return programLevel !== null;
  }

  public static async GetAcademicLoadCreditsBySemester(
    prisma: PrismaClient,
    programId: number,
    semesterNumber: number,
    programLevelId: number
  ) {
    return await prisma.academicLoadSemester.findUnique({
      where: {
        programId_semesterNumber_programLevelId: {
          programId,
          semesterNumber,
          programLevelId,
        },
      },
      select: { minCredits: true, maxCredits: true },
    });
  }

  public static async GetProgramsByFacultyId(facultyId: number, prisma: PrismaClient) {
    return await prisma.program.findMany({
      where: { facultyId: facultyId },
      select: { id: true, name: true, phone: true, programType: true, description: true }
    });

  }

  public static async GetAcademicLoadCreditsByGPA(
    prisma: PrismaClient,
    programId: number,
    cgpa: number
  ) {
    return await prisma.academicLoadGPA.findFirst({
      where: {
        programId,
        minGpa: { lte: cgpa },
        maxGpa: { gte: cgpa },
      },
      select: { minCredits: true, maxCredits: true },
    });
  }
}
